---
device_type: ''
serial_no: ''
usb_port_id: ''

initial_reset: False  # True

rgb_camera:
  profile: '848x480x15'
color_qos: "SENSOR_DATA"

depth_module:
  profile: '848x480x30'
  emitter_enabled: 1
  emitter_on_off: false
depth_qos: "SENSOR_DATA"
depth_info_qos: "SYSTEM_DEFAULT"

infra_qos: "SENSOR_DATA"

enable_depth:  true
enable_color:  true
enable_accel:  false
enable_gyro:   false
enable_infra1: false
enable_infra2: false

pointcloud:
  enable: false 
  pointcloud_qos: "SENSOR_DATA"

pointcloud_texture_index: 0
pointcloud_texture_stream: RS2_STREAM_ANY

enable_sync: true
align_depth: false


decimation_filter:
        enable: true
        filter_magnitude: 3

hole_filling_filter:
        enable: false

clip_distance: 9.0
