---
vicon_bridge:
        ros__parameters:
                publish_specific_segment: True
                target_subject_name: "laptop_realsense_true"
                target_segment_name: "laptop_realsense_true"
                world_frame_id: "world"
                tf_namespace: "vicon"
                host_name: "192.168.1.115:801"
                update_rate_hz: 125.0
                stream_mode: "ServerPush"

noisy_vicon:
        ros__parameters:
                epsilon_R_per_frame: 0.0006 # 0.0006 # 0.0012 # 1 degree / second 
                epsilon_t_per_frame: 0.0005 # 0.0005 # 0.0010 # 20 mm / second
                update_rate_hz: 30.0


