---
vicon_bridge:
        ros__parameters:
                publish_specific_segment: False 
                target_subject_name: "laptop_realsense"
                target_segment_name: "laptop_realsense"
                world_frame_id: "world"
                tf_namespace: "vicon"
                host_name: "192.168.1.115:801"
                update_rate_hz: 125.0
                stream_mode: "ServerPush"
