---
device_type: ''
serial_no: ''
usb_port_id: ''

initial_reset: False  # True

rgb_camera:
  profile: '640x480x15'
color_qos: "SENSOR_DATA"

depth_module:
  profile: '640x480x30'
  emitter_enabled: 1
  emitter_on_off: false
depth_qos: "SENSOR_DATA"
depth_info_qos: "SYSTEM_DEFAULT"

infra_qos: "SENSOR_DATA"

enable_accel: false
enable_color: true
enable_depth: true
enable_gyro: false
enable_infra1: false
enable_infra2: false

pointcloud:
  enable: true
  pointcloud_qos: "SENSOR_DATA"

pointcloud_texture_index: 0
pointcloud_texture_stream: RS2_STREAM_ANY

enable_sync: false
align_depth: false


decimation_filter:
        enable: true
        filter_magnitude: 3
